
package pe.PagoBruto;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PagoBrutoDao", targetNamespace = "http://PagoBruto.pe/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PagoBrutoDao {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calcularpagototal", targetNamespace = "http://PagoBruto.pe/", className = "pe.PagoBruto.Calcularpagototal")
    @ResponseWrapper(localName = "calcularpagototalResponse", targetNamespace = "http://PagoBruto.pe/", className = "pe.PagoBruto.CalcularpagototalResponse")
    @Action(input = "http://PagoBruto.pe/PagoBrutoDao/calcularpagototalRequest", output = "http://PagoBruto.pe/PagoBrutoDao/calcularpagototalResponse")
    public double calcularpagototal(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

}
